Env/src/PeriodicoDB/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin
from Registros.views import BusquedaMunicipio, BusquedaArma
from home.views import DepDetail

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include('home.urls', namespace='appHome')),
    url(r'^registro/', 'home.views.registro', name='Registro'),
    url(r'^$', 'home.views.home', name='home'),
    url(r'^regArmas/', 'Armas.views.Arma', name='arma'),
    url(r'^regLocal/', BusquedaMunicipio, name='Local'),
    url(r'^regArma/', BusquedaArma, name='Arma'),
    url(r'^registros/', include('Registros.urls',namespace='registros')),
    url(r'^logout/','home.views.cerrar', name='logout'),
    url(r'^signin/','home.views.inicio', name='inicio'),
    url(r'^estadisticas/', 'home.views.estadisticas', name='estadisticas'),
    url(r'^(?P<pk>\d+)$',DepDetail.as_view(),name='mapa'),
    url(r'^acerca/','home.views.acerca', name='acerca'),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

Env/src/Registros/urls.py
from django.conf.urls import url
from .views import (
	registro,
	lista, 
	RegistroDetail, 
	RegistroUpdate,
	correcto,
	BuscarPorNombre
	)

urlpatterns = [

	url(r'^$',registro,name='reg'),
	url(r'^list',lista, name = 'list'),
	url(r'^(?P<pk>\d+)$', RegistroDetail.as_view(), name='detail'),
	url(r'^editar/(?P<pk>\d+)$',RegistroUpdate.as_view(), name = 'edit'),
	url(r'^msg/$',correcto, name = 'msg'),
	url(r'^BuscarNombre', BuscarPorNombre, name='Nombre'),
]

Env/src/home/urls.py
from django.conf.urls import url
from .views import UserDetail, lista, UserUpdate, privado
from Registros.views import listaDetalles, detallesUser
from .views import (

	UserDetail,
	lista,
	UserUpdate,
	privado,
	permisos,
	cambioPass,
	)

urlpatterns = [

	url(r'^list',lista, name = 'list'),
	url(r'^(?P<pk>\d+)$', UserDetail.as_view(), name='detail'),
	url(r'^editar/(?P<pk>\d+)$', UserUpdate.as_view(), name='edit'),
	url(r'^$', privado, name = 'perfil'),
	url(r'^perm', permisos, name='403'),
	url(r'^detalles',listaDetalles,name='detail_list'),
	url(r'^actividades/(?P<vID>\d+)$', detallesUser, name = 'detailList'),
	url(r'^pass', cambioPass, name = 'pass'),

]

Env/src/Armas/models.py
from __future__ import unicode_literals
from django.db import models

class Arma(models.Model):

	Categoria_Choices =(
			('Fg','Arma de Fuego'),
			('Bn','Arma Blanca'),
			('Ot','Otro'),
		)

	id = models.AutoField(primary_key=True)
	calibre = models.CharField(max_length=20, blank=True, null=True)	
	marca = models.CharField(max_length=45, blank=True, null=True)
	categoria = models.CharField(max_length=2,choices=Categoria_Choices, default='Ot')
	objeto = models.CharField(max_length=45)	
	
	def __unicode__(self):
		return self.objeto

Env/src/Registros/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Registro(models.Model):	
	id = models.AutoField(primary_key=True)
	Sexo_Choices =(
			('M','Masculino'),
			('F','Femenino'),
			('D','Desconocido'),
		)
	
	nombres = models.CharField(max_length=55, default = 'xx')
	apellidos = models.CharField(max_length=55, default = 'xx')
	edad = models.SmallIntegerField(blank=True, null=True)
	muerto = models.BooleanField(null=None)	
	profesion = models.CharField(max_length=45, blank=True, null=True)
	cui = models.CharField(max_length=13, blank=True, null= True)
	sexo = models.CharField(max_length=2,choices=Sexo_Choices, default='D')
	ubicacion = models.TextField()

	no_casquillos = models.SmallIntegerField(blank=True, null=True)
	serial = models.CharField(max_length=45, blank=True,null=True)
	
	fiscal = models.CharField(max_length=60, blank=True, null=True)
	fecha = models.DateTimeField()
	fecha_registro = models.DateTimeField(auto_now=False, auto_now_add=True)
	descripcion = models.TextField()
	is_active = models.BooleanField(default = True)
	movil = models.CharField(max_length=100)
	no_expediente = models.CharField(max_length=40)

	def __unicode__(self):
		return str(self.id)

	def get_full_name(self):
		return self.nombres + " " + self.apellidos

	Municipio = models.ForeignKey('localizaciones.Municipio')
	Arma = models.ForeignKey('Armas.Arma')

	

class Actividad(models.Model):
	id = models.AutoField(primary_key=True)
	Registro_id = models.ForeignKey('Registro')
	Usuario_id = models.ForeignKey('home.Usuario')
	actividad = models.CharField(max_length=45)
	fecha = models.DateTimeField(auto_now=False,auto_now_add=True)

	verbose_name = 'Actividades'

Env/src/Armas/forms.py
from django import forms
from .models import Arma
from django.contrib.admin import widgets

class ArmaForm(forms.ModelForm):
	class Meta:
		model = Arma

		fields = ["categoria",
					"objeto",
					"calibre",
					"marca",					
				]	

	def __init__(self, *args, **kwargs):
		super(ArmaForm, self).__init__(*args, **kwargs)

		self.fields['objeto'].widget = forms.TextInput(attrs={
			'placeholder' : 'Clase, ejemplo: Rifle de Asalto'
			})

		self.fields['marca'].widget = forms.TextInput(attrs={
			'placeholder' : 'Ejemplo: Bersa'
			})

Env/src/Registros/forms.py
from django import forms
from .models import Registro
from django.contrib.admin import widgets
from datetimewidget.widgets import DateTimeWidget

class RegistroForm(forms.ModelForm):

	class Meta:
		model = Registro

		widgets = {
            'fecha': DateTimeWidget(usel10n = True, bootstrap_version=3)
        }	

		fields = ["Arma",
					"no_casquillos",	
					"serial",				
					"nombres",
					"apellidos",
					"edad",
					"muerto",
					"profesion",
					"cui",
					"sexo",
					"ubicacion",
					"fiscal",
					"fecha",
					"descripcion",
					"movil",
					"no_expediente",
					"Municipio",
												
			]

	def __init__(self, *args, **kwargs):
		super(RegistroForm, self).__init__(*args, **kwargs)

		self.fields['ubicacion'].widget = forms.Textarea(attrs={
			'placeholder' : 'Escriba direccion exacta o una referencia a la misma.'
			})

		self.fields['descripcion'].widget = forms.Textarea(attrs={
			'placeholder' : 'Nota de la parte policial.'
			})

Env/src/home/forms.py
#encoding: utf-8

from django import forms
from .models import Usuario
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, authenticate, logout

class UserCreationForm(forms.ModelForm):
    """A form for creating new users. Includes all the required
    fields, plus a repeated password."""
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password1 = forms.CharField(label='Confirmar Password', widget=forms.PasswordInput)
 
    class Meta:
        model = Usuario
        fields = ['nombre', 'apellidos', 'institucion','nombre_usuario','correo']

    def clean_password1(self):
        # Check that the two password entries match
        password = self.cleaned_data.get("password")
        password1 = self.cleaned_data.get("password1")
        if password and password1 and password != password1:
            raise forms.ValidationError("Las contraseñas no coinciden.")
        if password1 and password and len(password) < 8:
            raise forms.ValidationError("Ingrese una contraseña mas larga.")
        return password1

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(UserCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data.get("password1"))
        if commit:
            user.save()
            
        return user

# class UserChangeForm(forms.ModelForm):
#     """A form for updating users. Includes all the fields on
#     the user, but replaces the password field with admin's
#     password hash display field.
#     """
#     password = forms.CharField(label='Password', widget=forms.PasswordInput)
#     password1 = forms.CharField(label='Confirmar Password', widget=forms.PasswordInput)
 
#     class Meta:
#         model = Usuario
#         fields = ['nombre', 'apellidos']

#     def clean_password1(self):
#         # Check that the two password entries match
#         password = self.cleaned_data.get("password")
#         password1 = self.cleaned_data.get("password1")
#         if password and password1 and password != password1:
#             raise forms.ValidationError("Las contraseñas no coinciden.")
#         if password1 and password and len(password) < 8:
#             raise forms.ValidationError("Ingrese una contraseña mas larga.")
#         return password1

#     def save(self, commit=True):
#         # Save the provided password in hashed format
#         user = super(UserChangeForm, self).save(commit=False)
#         user.set_password(self.cleaned_data.get("password1"))
#         if commit:
#             user.save()
            
#         return user

class UserChangeForm(forms.Form):

    #actual_pass = forms.CharField(label = 'Contraseña actual',widget=forms.PasswordInput())
    password = forms.CharField(label='Password',widget=forms.PasswordInput())
    password1 = forms.CharField(label='Confirmar password',widget=forms.PasswordInput())
    
    # def clean_actual_pass(self,vPass):
    #     actual_pass = self.cleaned_data.get("actual_pass")

    #     if actual_pass and vPass and actual_pass == vPass:

    #         raise forms.ValidationError("Ingrese su contraseña actual.")

    #     return actual_pass

    def clean_password1(self):
        # Check that the two password entries match
        password = self.cleaned_data.get("password")
        password1 = self.cleaned_data.get("password1")

        if password and password1 and password != password1:

            raise forms.ValidationError("Las contraseñas no coinciden.")

        if password1 and password and len(password) < 8:

            raise forms.ValidationError("Ingrese una contraseña mas larga.")

        return password1

class InicioForm(forms.Form):
	usuario = forms.CharField()
	password = forms.CharField(widget=forms.PasswordInput())

Env/src/Armas/views.py
from django.shortcuts import render, redirect
from .forms import ArmaForm
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect

# Create your views here.
@login_required(login_url='inicio')
def Arma(request):
	tipo = request.user.Tipo_Usuario_id.id

	if tipo == 4 or tipo == 3:
		form = ArmaForm(request.POST or None)
		context = {
			"form":form,
			"titulo":"Registro de Armas"
		}

		if form.is_valid():
			form.save()
			return redirect('registros:reg')


		return render(request,'armas.html',context)
	else:
		redirect('appHome:403')

def VistaArma(request):
		id_Categoria = request.GET['id']
		muni = Municipio.objects.filter(Departamento_id= id_Departamento)
		data = serializers.serialize('json', muni, fields = ('municipio'))
		return HttpResponse(data, content_type='application/json')

Env/src/Registros/views.py
from django.shortcuts import render, redirect
from .forms import RegistroForm
from .models import Registro, Actividad
from django.core.urlresolvers import reverse_lazy, reverse
#from home.models import Usuario
from django.core import serializers
from django.http import HttpResponse, HttpResponseRedirect
from localizaciones.models import Municipio, Departamento
from Armas.models import Arma
from home.models import Usuario
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic.detail import DetailView
#from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import UpdateView
from django.http import HttpResponseRedirect
from django.views.generic.edit import ModelFormMixin

class RegistroDetail(DetailView):
	model = Registro
	template_name = 'registro_detail.html'

	@method_decorator(login_required)
	def dispatch(self,request, *args, **kwargs):
		tipo = request.user.Tipo_Usuario_id.id

		if tipo == 4 or tipo == 3:
			return super(RegistroDetail, self).dispatch(request,*args,**kwargs)

		return redirect('appHome:403')

class RegistroUpdate(UpdateView):
	model = Registro
	template_name = 'registro_update.html'
	success_url = reverse_lazy('registros:list')
	fields = [

		"nombres",
		"apellidos",
		"edad",
		"muerto",
		"profesion",
		"cui",
		"sexo",
		"ubicacion",
		"fiscal",
		"Municipio",
		"Arma",
		"no_casquillos",
		"serial",
		"fecha",
		"descripcion",
		"is_active",
		"movil",
		"no_expediente"

		]


	def form_valid(self, form):

		self.object = form.save()
		rID = self.object
		vID = self.request.user

		a = Actividad(Registro_id = rID, Usuario_id = vID, actividad = "Modificado")
		a.save()

		return super(RegistroUpdate, self).form_valid(form)

	def get_context_data(self, **kwargs):
		
		context = super(RegistroUpdate, self).get_context_data(**kwargs)
		Departamentos = Departamento.objects.all()
		Municipios = Municipio.objects.all()
		Armas = Arma.objects.all()

		context.update({
			"Armas":Armas, 
			"Departamentos":Departamentos,
			"Municipios": Municipios,
			})

		return context

	@method_decorator(login_required)
	def dispatch(self,request, *args, **kwargs):
		
		tipo = request.user.Tipo_Usuario_id.id

		if tipo == 4 or tipo == 3:

			return super(RegistroUpdate, self).dispatch(request,*args,**kwargs)

		return redirect('appHome:403')


@login_required(login_url='inicio')
def registro(request):

	tipo = request.user.Tipo_Usuario_id.id

	if tipo == 4 or tipo == 3:
		form = RegistroForm(request.POST or None)
		Departamentos = Departamento.objects.all()
		Municipios = Municipio.objects.all()
		Armas = Arma.objects.all()

		context = {
			"form" :form,
			"Armas" : Armas,
			"Departamentos" : Departamentos,
			"Municipios" : Municipios,
			"titulo": "Registros"
		}

		if form.is_valid():
			rID = form.save()
			vID = request.user
			#rID = Registro.objects.latest('id')
			print vID," ",rID
			a = Actividad(Registro_id=rID,Usuario_id=vID,actividad="Creado")
			a.save()
			return redirect("registros:msg")

		return render(request,'registros.html',context)

	return redirect('appHome:403')

@login_required(login_url='inicio')
def lista(request):
	tipo = request.user.Tipo_Usuario_id.id
	registros = Registro.objects.all()
	if tipo == 4 or tipo == 3:
		context = { 
			"registros": registros,
			"bandera": True, 
			}

		return render(request,"registro_list.html",context)

	if tipo == 2:
		registros = Registro.objects.filter(is_active=True)
		context = {
			"registros": registros,
			"bandera": False,
			}

		return render(request,"registro_list.html",context)

	return redirect('appHome:403')

@login_required(login_url='inicio')
def listaDetalles(request):
	tipo = request.user.Tipo_Usuario_id.id

	if tipo == 4 or tipo == 3:
		detalles = Actividad.objects.all()

		context = {"detalles": detalles}
		return render(request,"detalles_list.html",context)

	return redirect("appHome:403")

@login_required(login_url='inicio')
def detallesUser(request,vID):
	tipo = request.user.Tipo_Usuario_id.id

	if tipo == 4 or tipo == 3:
		detalles = Actividad.objects.filter(Usuario_id=vID)
		usuario = Usuario.objects.filter(id=vID)

		context = {
			"detalles": detalles,
			"usuario": usuario,
		}
		return render(request,"detailList.html",context)

	return redirect("appHome:403")	

def BusquedaMunicipio(request):
	id_Departamento = request.GET['id']
	muni = Municipio.objects.filter(Departamento_id= id_Departamento)
	data = serializers.serialize('json', muni, fields = ('municipio'))
	return HttpResponse(data, content_type='application/json')

def BusquedaArma(request):
		id_Arma = request.GET['id']
		Armas = Arma.objects.filter(categoria = id_Arma)
		data = serializers.serialize('json', Armas, fields = ('objeto','marca','calibre'))
		return HttpResponse(data, content_type='application/json')

@login_required(login_url='inicio')
def correcto(request):
	tipo = request.user.Tipo_Usuario_id.id
	if tipo == 4 or tipo == 3:
		return render(request, 'agregado.html', {})

	return redirect('appHome:403')

def BuscarPorNombre(request):
	search = request.GET['buscar']
	seleccionado = request.GET['select']

	if seleccionado == "Nombre":
		Reg_Nombre = Registro.objects.filter(nombres__contains = search)
		data = serializers.serialize('json', Reg_Nombre, fields = ('Arma','nombres','apellidos','edad',
																'sexo','ubicacion','fecha','descripcion','Municipio'))
	elif seleccionado == "Apellidos":	
		Reg_Nombre = Registro.objects.filter(apellidos__contains = search)
		data = serializers.serialize('json', Reg_Nombre, fields = ('Arma','nombres','apellidos','edad',
																'sexo','ubicacion','fecha','descripcion','Municipio'))
	elif seleccionado == "Edad":	
		Reg_Nombre = Registro.objects.filter(edad__contains = search)
		data = serializers.serialize('json', Reg_Nombre, fields = ('Arma','nombres','apellidos','edad',
																'sexo','ubicacion','fecha','descripcion','Municipio'))
	elif seleccionado == "Sexo":	
		Reg_Nombre = Registro.objects.filter(sexo__contains = search)
		data = serializers.serialize('json', Reg_Nombre, fields = ('Arma','nombres','apellidos','edad',
																'sexo','ubicacion','fecha','descripcion','Municipio'))
	elif seleccionado == "Fecha":	
		Reg_Nombre = Registro.objects.filter(fecha__contains = search)
		data = serializers.serialize('json', Reg_Nombre, fields = ('Arma','nombres','apellidos','edad',
																'sexo','ubicacion','fecha','descripcion','Municipio'))


	return HttpResponse(data, content_type='application/json')

Env/src/templates/acerca.html
{% extends 'base.html' %}

{% block content %}

<div id="section">
  <div id="segundoBloque">
    <div class = "titulo">
      <h1>Acerca de</h1>
    </div>
    <div class = "texto">
      <br/>
      <p> Como una forma de socializar el trabajo de la la Policía Nacional Civil a la población guatemalteca, el portal de Estadísticas de la PNC provee datos actualizados de los hechos violentos en el territorio nacional. La base de datos, alimentada con el producto de la investigación de las primeras 72 horas posteriores al hecho, da a investigadores sociales, periodistas y analistas de violencia un panorama constante del comportamiento criminal.
     <br/>
     <br/>
      La máxima utilidad del portal de Estadísticas de la PNC radica en sus filtros. Estos al ser aplicados por el usuario, facilita la diferenciación de análisis territorial en lo local. Así, aunque dos espacios compartan características, la separación de ambos mediante sus datos finales permitirá evaluar su evolución, la detección de patrones y la manera de abordarlos.
      <br/>
      <br/>
      Proyecto financiado por el Fondo para Investigaciones Periodísticas (FIJ) de Washington, DC en alianza con la Universidad Rafael Landívar de Quetzaltenango.
      <br/>
      <br/>
      <div class="firma">
        <div class = "firmaBold">
          Francisco Rodriguez
        </div>
        elPeriodico de Guatemala
      </div>
      </p>
      <p font-weight= "bold">
        Desarrolladores:
          <br/>
          <a href="mailto:carlosfipq@gmail.com">    Carlos Garcia Robles</a>
          <br/>
          <a href="mailto:malvinjazz@hotmail.com">    Melvin Juarez Amezquita</a>
          <br/>
          <a href="mailto:justojul23@hotmail.com">    Justo Rivera Pac</a>
          <br/>
          <a href="mailto:chofo2003@hotmail.com">   Rodolfo Rodas Oregel</a>
      </p>
    </div>
  </div>
</div>


{% endblock %}

Env/src/templates/armas.html
{% extends 'base.html' %}

{% block content %}

<!-- onsubmit='this.reset()' -->
<div id="section">
  <div id="BloqueInicio">
            <div class = "title">
      <h2>Nueva arma</h2>
    </div>
    <div class = "camposForms">
      <form method = 'POST', action='' >
	{% csrf_token %}
	{{form.categoria}}<br/>
	<div id='fg'>
		<label>Calibre:</label>
		{{form.calibre}}<br/>
		<label>Marca:</label>
		{{form.marca}}<br/>
	</div>

	<label>Objeto:</label>
		{{form.objeto}}<br/>


	<br/>
	<hr>
  <br/>
  <br/>
	<input type='submit' value='Registrar Arma'>

{% endblock %}

{% block js %}
{% csrf_token %}
	<script type="text/javascript">
		$('#id_categoria').on('change', funcion);
		$formulario_Fg=$('#fg');
		$formulario_Fg.hide();


		function funcion(){
			$formulario_Fg.hide();

			var id = $(this).val();

			if(id == 'Fg'){
				$formulario_Fg.show();
			}
		}
	</script>


</form>

</div>
  </div>
</div>
{% endblock %}

Env/src/templates/cambioPass.html
{% extends 'base.html' %}


{% block content %}




<div id="section">
  <div id="BloqueInicio">
		<div class = "title">
      <h2>Cambio de contraseña</h2>
    </div>
    <div class = "formularios">
			<form method = 'POST', action = ''>

				{% csrf_token %}
				{{form.as_p}}

				<input type='submit' value='Actualizar'>

			</form>
    </div>

  </div>
</div>

{% endblock %}

Env/src/templates/detailList.html
{% extends 'base.html' %}

{% block content %}

<div id="section">
		<div class = "title">
			<h1>Datos modificados por {{usuario.get_full_name}}</h1>
		</div>
		<div class = "alineacionCentral">
			<table class="table">
        <tr>
          <td>Usuario</td>
          <td>Accion</td>
          <td>Registro</td>
          <td>Fecha</td>
        </tr>
        {% for dato in detalles %}
        <tr>
          <td><i>{{dato.Usuario_id}}</i></td>
          <td><i>{{dato.actividad}}</i></td>
          <td><i>{{dato.Registro_id}}</td>
          <td><i>{{dato.fecha}}</i></td>
				</tr>
        {% endfor %}
      </table>
		</div>
</div>


{% endblock %}

Env/src/templates/detalles_list.html
{% extends 'base.html' %}

{% block content %}


    <div id="section">
    		<div class = "title">
    			<h2>Actividades del usuario</h2>
    		</div>
    		<div class = "alineacionCentral">
    			<table class="table">
            <tr>
              <td>Usuario</td>
              <td>Accion</td>
              <td>Registro</td>
              <td>Fecha</td>
              <td>Historial</td>
            </tr>
            {% for dato in detalles %}
            <tr>
              <td><i>{{dato.Usuario_id}}</i></td>
              <td><i>{{dato.actividad}}</i></td>
              <td><i>{{dato.Registro_id}}</td>
              <td><i>{{dato.fecha}}</i></td>
              <td><a href = {% url 'appHome:detailList' dato.Usuario_id.id %}>Ver todos los registros modificados por este usuario.</a></td>
    				</tr>
            {% endfor %}
          </table>
    		</div>
    </div>

{% endblock %}

Env/src/templates/perfil_a.html
{% extends 'base.html' %}

{% block content %}


<div id="section">
		<div class = "title">
			<h1>Bienvenido {{user.get_full_name}}</h1>
		</div>
		<div class = "alineacionAlCentro">
			<table class="table">
				<tr>
						<td>Nombre de usuario</td>
						<td><i>{{user.nombre_usuario}}</i></td>
				</tr>
				<tr>
						<td>Correo</td>
						<td><i>{{user.correo}}</i></td>
				</tr>
				<tr>
						<td>Institucion</td>
						<td><i>{{user.institucion}}</i></td>
				</tr>
				<tr>
						<td>Ultima conexion</td>
						<td><i>{{user.ultima_conexion}}</i></td>
				</tr>
				<tr>
						<td>Tipo de Usuario</td>
						<td><i>{{user.Tipo_Usuario_id}}</i></td>
				</tr>
			</table>
			<table>
				<tr>
					<a href= {% url 'appHome:pass' %}>Cambiar pass</a>
					<a> | </a>
					<a href = {% url 'appHome:list' %}>Usuarios</a>
					<a> | </a>
					<a href= {% url 'registros:list' %}>Registros</a>
					<a> | </a>
					<a href = {% url 'appHome:detail_list' %}>Actividades</a>
				</tr>
			</table>
		</div>
</div>




{% endblock %}

Env/src/templates/perfil_p.html
{% extends 'base.html' %}

{% block content %}

<div id="section">
		<div class = "title">
			<h1>Bienvenido {{user.get_full_name}}</h1>
		</div>
		<div class = "alineacionAlCentro">
			<table class="table">
				<tr>
						<td>Nombre de usuario</td>
						<td><i>{{user.nombre_usuario}}</i></td>
				</tr>
				<tr>
						<td>Correo</td>
						<td><i>{{user.correo}}</i></td>
				</tr>
				<tr>
						<td>Institucion</td>
						<td><i>{{user.institucion}}</i></td>
				</tr>
				<tr>
						<td>Ultima conexion</td>
						<td><i>{{user.ultima_conexion}}</i></td>
				</tr>
				<tr>
						<td>Tipo de Usuario</td>
						<td><i>{{user.Tipo_Usuario_id}}</i></td>
				</tr>
			</table>
			<table>
				<tr>
					<a href= {% url 'appHome:pass' %}>Cambiar pass</a>
					<a> | </a>
					<a href= {% url 'registros:list' %}>Registros</a>
					<a> | </a>
					<a href = {% url 'appHome:detail_list' %}>Actividades</a>
				</tr>
			</table>
		</div>
</div>




{% endblock %}

Env/src/templates/usuario_list.html
{% extends 'base.html' %}

{% block content %}

<div id="section">
  <div class = "title">
    <h1 style="color:black;">Usuarios</h1>
  </div>
  <!-- <div id="dobleBloque">
    <div class = "bloqueUno">
      {% for dato in usuarios %}
          <li>
              <p>{{ dato.nombre }}</p>
          </li>
      {% endfor %}
    </div>
    <div class = "bloqueDos">
      {% for dato in usuarios %}
        <p>
          <a href={% url 'appHome:detail' dato.id %}>Ver</a>
          <a> | </a>
          <a href={% url 'appHome:edit' dato.id %}>Editar</a>
          <a> | </a>
          <a href={% url 'appHome:detailList' dato.id %}>Ver actividades del usuario</a>
        </p>
      {% endfor %}
    </div> -->


  <!-- </div> -->




  <div class="alineacionCentral">
    <table class="table">

      {% for dato in usuarios %}
      <tr>
        <td>{{ dato.nombre }}</td>
        <td><a href={% url 'appHome:detail' dato.id %}>Ver</a>
        </td>
        <td>
          <a href={% url 'appHome:edit' dato.id %}>Editar</a>

        </td>
        <td>
          <a href={% url 'appHome:detailList' dato.id %}>Ver actividades del usuario</a>

        </td>
      </tr>
      {% endfor %}
  </div>
  </table>
</div>


<!-- gify icons -->


{% endblock %}